services:

  recruit:
    container_name: recruit_python
    image: recruit/python
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/srv # tip .表示当前目录 /srv表示目标目录，原本后面的:cached是不必要的
    tty: true
    deploy:
      resources:
        limits:
          memory: 512M

